### ISSUE TITLE
SyntaxError when using v7.0.0-pre8

### ISSUE THREAD

**Issue by arghlolrofl** [ms-iot/node#10]
- **Version**: v7.0.0-pre8
- **Platform**: Windows 10 x64

Hi,

I just wanted to follow your guide from the [Hello Blinky App](https://developer.microsoft.com/de-de/windows/iot/samples/helloblinkynode) to install Node (Chakra) on my Desktop PC. I downloaded and installed the MSI-package and now I wanted to build the node module 'serialport' for my target platform (RasPi 3 with Windows 10 IoT).
My problem now is, that i can't get it to work. I verified the installation of Node (Chakra) with the command:
`node -v`
which shows the correct version: v7.0.0-pre8

But on every other command (e.g.: `node -e "console.log('Test');"` or `npm -v`) an error is being shown:

> SyntaxError: Expected identifier, string or number

P.S.: I already tried to use the arm version of your `node-serialport` [fork](https://github.com/ms-iot/node-serialport), but running the code on the RasPi3, when hitting the line 
`var SerialPort = require('./serialport.node');`
the application always exits, without printing an error.

P.P.S.: Just tried to update my installation of Node.js Tools for UWP Apps 1.5.4 to 1.5.5. But the result is the same when trying to run `npm -v`.

**Comment by munyirik** [comment]
Hi @arghlolrofl sorry for the delay. I'll look into this...

**Comment by munyirik** [comment]
For the first issue with SyntaxError, I cannot reproduce. I have the same version and this is what I see when I run the commands:
>E:\repos>node -v
v7.0.0-pre8

>E:\repos>node -e "console.log('Test');"
Test

Could you run "systeminfo" in a cmd window and let me know what the "OS Version" value is?

For the serialport issue, make sure you use serialport_WinIoT\console\arm\serialport.node in the zip file if you were not doing that already.

IIRC there's an issue on IoT Core when accessing onboard ports (UART) if you are not using a UWP app.

If you are connecting a USB serial device then you need to assign a name to the port before you use it since it's not done automatically (I'll document this soon on the ntvsiot repo):

* In SSH or PowerShell connected to your Pi, run `devcon status usb*`. When you do this, you should see a device similar to the one below:

   USB\VID_2341&PID_8036\5&3753427A&0&4  
   Name: USB Serial Device  
   Driver is running.
* Run `reg add "HKLM\SYSTEM\ControlSet001\Enum\usb\VID_2341&PID_8036\5&3753427A&0&4\Device Parameters" /v "PortName" /t REG_SZ /d "COM5" /f`. (change the "usb\VID_2341&PID_8036\5&3753427A&0&4" string with what you have)
* Run `shutdown /r /t 0` to reboot the device.
* When the device restarts, you will be able to use COM5 in your code (note that you can use a different number too, doesn't have to be 5).

Lastly, these steps are only required if you're running node via command line. If you're using Node.js UWP you can skip these steps. The only 'strange' thing you need to do with serialport is patch it (this is temporary) so it works in a UWP app. You can see the steps to do that [here](https://developer.microsoft.com/en-us/windows/iot/samples/j5servocontroller) (Look for "Update npm packages").

**Comment by IoTGirl** [comment]
@arghlolrofl As you have not responded to the last request for details I am closing this issue as stale/abandoned
